# Generated by Django 2.0.1 on 2018-03-13 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('filelocation', models.FileField(upload_to='csv_file/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fileurl', models.CharField(default='N/A', max_length=255)),
            ],
        ),
    ]
